### ISSUE TITLE
Upload attempt fails - OS X 'El Capitan'

### ISSUE THREAD

**Issue by avluis** [konektlabs/konekt-dash-arduino-integration#1]
Attempting to upload to a Dash Pro Beta results in the following (only the relevant portion included):

```
python /Users/avluis/Documents/Arduino/hardware/konekt.io/dash/tools/update_dash.py /var/folders/by/j72slykd6nlfsn8h922xbm2r0000gn/T/build7378603789835342231.tmp/konekt_dash_helloworld.cpp.bin 
Traceback (most recent call last):
  File "/Users/avluis/Documents/Arduino/hardware/konekt.io/dash/tools/update_dash.py", line 26, in <module>
    import hid
ImportError: No module named hid
```

Is this a python or Arduino issue - I ask since this is the latest Mac OS X and it could be that as well.

**Comment by taylorwc** [comment]
I am also experiencing the same issue

**Comment by rbalik** [comment]
Try doing a `pip install cython` and `pip install hidapi`

**Comment by rbalik** [comment]
We're working on getting this all packaged up so that it's not so bumpy

**Comment by pathogan** [comment]
Hi - this might be a bit easier. Here is an OS X specific build of the konekt.io arduino integration folder, with all of the dependencies included. Simply extract and add the "konekt.io" directory to your Arduino-->hardware location. This folder will fully replace any "konekt.io" folder you might already have in your hardware directory. No need to install python, cython, hidapi, or any of the other dependencies.

[mac_os_x_konekt.io.zip](https://github.com/konektlabs/konekt-dash-arduino-integration/files/89572/mac_os_x_konekt.io.zip)

**Comment by taylorwc** [comment]
I tried replacing the konekt.io directory with the folder in the zip file above, still no luck! I have both cython and hidapi installed already, but I'm wondering if I'm having an issue with my $PATH

**Comment by pathogan** [comment]
Do you get the same errors with the new konekt.io directory? That version of the folder should not require python, cython, hidapi or any dependencies. Make sure to fully remove the konekt.io directory before adding this new one, and restart your Arduino application before trying again.

**Comment by taylorwc** [comment]
Ahhh. I hadn't restarted the Arduino app. That removed the dependency error. Unfortunately it queued up another error, all it says in the log is 'block write failed' -- I have pushed the PGM button (light flashing as well), but no luck. Thanks for the help.

**Comment by pathogan** [comment]
Ha - sorry, the "block write failed" message is just a logging bug on our part. Believe it or not, that actually means it worked!

**Comment by taylorwc** [comment]
Ha--that's awesome. OK, thanks for helping. OK with me to close this issue.

**Comment by patatkonektdata** [comment]
Go for it!

**Comment by taylorwc** [comment]
oops i think either you or luis will have to close.

**Comment by pathogan** [comment]
@avluis, just wanted to make sure you were able to get up and running with this solution.

**Comment by avluis** [comment]
@pathogan I had initially just given up and put together a Windows system (I had a build pending anyways) to get started - I'll try out the attached file and report back - should have no problem if it worked for @taylorwc on his copy of OS X.
